name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run rename_index_files
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          host: storage.bunnycdn.com
          user: open-meteo-staging
          password: ${{ secrets.ftp_password_staging }}
          localDir: "build"
      - run: "curl --request POST --url https://api.bunny.net/pullzone/277769/purgeCache --header 'AccessKey: ${{ secrets.bunny_api_key }}' --header 'content-type: application/json'"
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
