name: Build and Deploy

on:
  push:
    tags:
      - "*.*.*"

# Allow one concurrent deployment
concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run rename_index_files
      - name: Upload ftp
        uses: genietim/ftp-action@v4.0.1
        with:
          host: storage.bunnycdn.com
          user: open-meteo
          password: ${{ secrets.ftp_password }}
          localDir: "build"
          remoteDir: ""
      - run: "curl --request POST --url https://api.bunny.net/pullzone/1309127/purgeCache --header 'AccessKey: ${{ secrets.bunny_api_key }}' --header 'content-type: application/json'"
